#数据库链接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-new-learn?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 13456
  devtools:
    add-properties: false