logging:
  config: classpath:logback.xml
  level:
    cn.hd.controller: info



#数据库链接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-new-learn?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  devtools:
    add-properties: false